# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 04:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2, unique=True)),
            ],
            options={
                'db_table': 'country',
                'verbose_name_plural': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'genre',
                'verbose_name_plural': 'genres',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('rating', models.FloatField(default=0)),
                ('trailer', models.URLField()),
                ('cover', models.ImageField(upload_to='')),
                ('link_to_watch', models.URLField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('duration', models.DurationField()),
                ('genres', models.ManyToManyField(blank=True, related_name='of_the_movie', to='movies.Genre', verbose_name='genres')),
                ('production_countries', models.ManyToManyField(related_name='of_production', to='movies.Country', verbose_name='production countries')),
            ],
            options={
                'db_table': 'movie',
                'ordering': ['date_added'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='of_the_actor', to='movies.Country', verbose_name='represented country')),
            ],
            options={
                'db_table': 'person',
                'verbose_name_plural': 'people',
            },
        ),
    ]
