# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Director', 'Director'), ('Actor', 'Actor')], max_length=30, unique=True)),
            ],
            options={
                'db_table': 'production_role',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='production_role',
            field=models.ManyToManyField(blank=True, related_name='in_movie_production', to='movies.ProductionRole', verbose_name='role in movie production'),
        ),
    ]
