# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 04:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20161019_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(blank=True, related_name='acted_in_the_movie', to='movies.Person', verbose_name='list of actors'),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_the_movie', to='movies.Person', verbose_name='director'),
        ),
    ]
