# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20161019_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_movies', to='movies.Person', verbose_name='director'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='movies', to='movies.Genre', verbose_name='genres'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='production_countries',
            field=models.ManyToManyField(related_name='movies', to='movies.Country', verbose_name='production countries'),
        ),
    ]
