# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20161019_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.DurationField(help_text='Format HH:MM:SS'),
        ),
    ]
