# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20161019_1809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['country'], 'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name'], 'verbose_name_plural': 'genres'},
        ),
    ]
