# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20161019_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='link_to_watch',
            field=models.URLField(blank=True, null=True),
        ),
    ]
