# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_person_date_of_death'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
        migrations.AddField(
            model_name='movie',
            name='key_actors',
            field=models.ManyToManyField(blank=True, related_name='movies', to='movies.Person', verbose_name='list of key actors'),
        ),
    ]
