# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_auto_20161020_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
