# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 08:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_person_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['country__name'], 'verbose_name_plural': 'countries'},
        ),
    ]
