# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_auto_20161021_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionrole',
            name='title',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
