# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 21:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_auto_20161024_2320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-date_added']},
        ),
    ]
