# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 20:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0021_auto_20161109_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favourite_movies', models.ManyToManyField(blank=True, related_name='users_favourite', to='movies.Movie', verbose_name='favourite movies')),
                ('liked_movies', models.ManyToManyField(blank=True, related_name='users_liked', to='movies.Movie', verbose_name='liked movies')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('watch_list', models.ManyToManyField(blank=True, related_name='users_added_watch_list', to='movies.Movie', verbose_name='watch list')),
            ],
        ),
    ]
