# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 20:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0025_auto_20161204_2241'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
    ]
