# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0027_auto_20161204_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='disliked_movies',
            field=models.ManyToManyField(blank=True, related_name='users_disliked', to='movies.Movie', verbose_name='disliked movies'),
        ),
    ]
