# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0028_profile_disliked_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='dislikes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='likes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
